# Default values for s3-sync-compress
replicaCount: 3

image:
  repository: huynguyen260398/s3-sync-compress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  test-nodes: "true"

podAntiAffinity:
  enabled: true
  type: required  # Can be 'required' or 'preferred'

aws:
  s3Bucket: "s3-sync-compress-bucket"
  s3Prefix: ""
  s3OutputBucket: "s3-sync-compress-bucket-results"
  s3OutputPrefix: ""
  region: "ap-southeast-1"
  accessKeyId: ""
  secretAccessKey: ""

# Health check configuration
healthCheck:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
